### PR TITLE
The color of the Completed and Compliting boxes are changed to violet

### PR DESCRIPTION
**Pull request by zmathe**
It is requested by Philippe to change the colour of the completed job status.

### CODE REVIEW

**Comment by msapunov** [comment]
We have already picture of violet color: https://raw.github.com/DIRACGrid/DIRACWeb/integration/dirac/public/images/monitoring/bad.gif
Could you please just replace the name of icon from "completed.gif" to "bad.gif"?

**Comment by zmathe** [comment]
I do not think it is a good idea, because the bad != completed... The colour is a bit difference. I propose to make darker the bad.gif and keep the completed.

**Comment by msapunov** [comment]
Don't pay attention on file names, they should be changed done.gif ->
green.gif, failed.gif -> red.gif
Yes, there is a tinny color difference, it happen because all the status
icons have a visible dark gradient on it. Icons are not the best just i
would like to have them in same style.

**Comment by zmathe** [comment]
Well if we decided to have different colour of the bad and completed statuses, we must have two different file name:
babala.gif, cccc.gif. If we decided the completed and bad are same then we use one file.

**Comment by msapunov** [comment]
As far as i remember these two statuses are not shown on the same page.
Status "Bad" is for SiteSummary page and it doesn't exists on
TransformationMonitoring page. Icon are used just for visual separation. If
you insist to have to slightly different violet colors, could you please
apply a dark gradient on it.
Do i understand correct and you dislike the name of a file? Or color also
matters for you?

**Comment by zmathe** [comment]
Well I prefer to do not have specific file names such as Bad, Completed, Done. It is better to have redbox, greenbox, violentbox files. Each file can have multiple statuses. For example: Completed, Compliting, Bad are using violentbox. If we decided to have different colour of the Completed and Bad, we must have a new file. For examlpe: lightviolent and violent.

As the colour agreed by Philippe and no one else complained it. I prefer to use the same colour and not do that:
cp bad.gif completed.gif 
You said in the previous mail to replace Bad.gif to Completed.gif. If I do that the pages which are using bad.gif, will not work, because the Bad.gif does not exist...

**Comment by msapunov** [comment]
Fine, we are both agree to rename icons. Renaming should be done in
different pull request. The point here is that icon in your pull request is
not in the same style with other icons used to display statuses. So, could
you please put gradient on your icon? Just do that and i'll merge you
request straight away.

**Pull request closed without merging**
