### PR TITLE
correcting the return value

### PR DESCRIPTION
**Pull request by zmathe**
the method should not render a page. It should return S_OK/S_ERROR every were.

### CODE REVIEW

**Comment by msapunov** [comment]
I understand what for you want to use static method, what is not clear for me is why you can't use it like:

```
def parseFormParams(self):
  params = request.params
  return self.__parseFormParams(params)
```

**Comment by zmathe** [comment]
As I said before i have to import the method in other module:
from dirac.controllers.systems.accountingPlots import parseFormParams
it means the params = request.params is undefined. The other possibility is to move the parseFormParams inside the controller:
@staticmethod
def parseFormParams(self, params)
   ....
so the parseFromParams(params) is a public method. It can be static whatever, it is not belongs to the controller. So it has an input parameter and an output parameters which is built by using a certain procedure. 
the __parseFromParams it is a method of the class, which is private:
def __parseFromParams(self):
   params = request.params
   return parseFormParams(params)

In your example I want to use the self.__parseFormParams(params) method. Is it clear now?

**Comment by zmathe** [comment]
A simple example:

> > > class A:
> > > ...   def __a(self):
> > > ...    params = 'zoli'
> > > ...    return self.b(params)
> > > ...   @staticmethod
> > > ...   def b(params):
> > > ...     return params + 'ka'
> > > ... 
> > > A.b('mamam')
> > > 'mamamka'

My case the b in not member of the class:

> > > class A:
> > > ...   def __a(self):
> > > ...    params = 'zoli'
> > > ...    return b(params)
> > > ... 
> > > def b(params):
> > > ...   return params + 'ka'
> > > ... 
> > > b('mamam')
> > > 'mamamka'

They are the two possibilities I have chosen the second.

**Comment by msapunov** [comment]
Ah, you want to use this code in another module, not in web controllers? Am i right? Cause otherwise params.request is always available.
Well i can't say it's very safe solution because in theory one can install DIRAC without installing DIRACWeb module but okay, up to you.

**Comment by zmathe** [comment]
I am using it from the Presenter.py web controller. I know the params.request is available. But in the presenter.py controller the params.request is different than the accountingPlots. I have a list of parameters so it means if I wanted to use the accountingPlots.py method I have to call it N times; where the N is the number of plots in the presenter page. It is better to call the controller once instead of N times. This was the simplest solution, it required minimal modification. It is a save solution as LHCbWebDIRAC required DIRACWeb.

**Pull request merged**
