### PR TITLE
moved from LHCbWeb to Web Core

### PR DESCRIPTION
**Pull request by msapunov**
Move all the Presenter related files from LHCbWeb to Web Core

### CODE REVIEW

**Comment by acasajus** [comment]
I think you're missing an entry in the web.cfg maybe?

**Comment by msapunov** [comment]
right. wait. will do that later

**Comment by acasajus** [comment]
If you push more commits to the same branch the pull request gets updated automatically. So just make the change in your local repo, push the change to the _presenter-to-core_ branch and that's it :)

**Comment by msapunov** [comment]
Oook, seems to be better, can you approve it now?

**Comment by acasajus** [comment]
I just deployed your branch on lhcb01.ecm.ub.es. Is it ok?

**Comment by msapunov** [comment]
Looks okay, apart from the fact that it's a LHCbWeb installation... can you install Dirac Core only? Core web.cfg

**Comment by acasajus** [comment]
Try now

On 18 May 2011 11:58, msapunov
reply@reply.github.com
wrote:

**Pull request merged**
