### PR TITLE
a few missing job status added to the production monitor page

### PR DESCRIPTION
**Pull request by zmathe**
This task belongs to the ticket 22.

### CODE REVIEW

**Comment by msapunov** [comment]
Zolthan, it's LHCb specific functionality therefor it should be released through the LHCbWeb release procedure i.e. you should commit it to SVN there is a production monitor page which overwrites the vanilla one.  Also, guess .DS_Store is not a part of release ;)
Ok. i'm closing this request without merging.

**Comment by zmathe** [comment]
Well this is useful for other VOs as well. BUT NOTE THE LHCBProduction.js are NOT USED. I fixed in the LHCbWebDIRAC and after I merged to the DIRACWeb.....

**Comment by zmathe** [comment]
Why the line commented:
    production
    {

# Production monitor = Production/LHCBProduction/display, Production monitoring, all

```
  Production monitor = jobs/ProductionMonitor/display, Production monitoring, all
  Requests manager = Production/ProductionRequest/display, Requests management, all
  Step manager = Production/ProductionStep/display, Step management, all
}
```

**Comment by msapunov** [comment]
The only VO which is using functionality from DIRAC production system and ProductionMonitor is ILC and they are complaining that the ProductionMonitoring page is created for LHCb. So actually this page must be even simplified.

The line is commented in LHCbWeb. In DiracWeb we don't have section called Production. So first of all it's wrong name as Philippe pointed it out, and second point - it's unfinished work. So i would recommend you to copy over your code to LHCBProduction.js which makes sense (actually all these statuses were already there but was deleted because of complains of users) rename this file and uncomment this string in web.cfg Also, i do remember that i was makes tests to actually add the functionality both on controller level and JS level to a basic webpage. So if you want, i can send you my code base of these tests, so based on which you can actually code and commit the difference between two pages and not a page as whole...

**Comment by zmathe** [comment]
My code in both place LHCbWeb and DIRACWeb. I only have to solve the web.cfg and the naming convention.

**Pull request closed without merging**
